### ISSUE TITLE
mseccfg/mseccnf clarification (4.6)

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-crypto#100]
Section 4.6 talks about `mseccfg` and also `mseccnf`, which is a CSR at address `0x390`. can you please clarify:

1. Are these the same thing?
2. Is the CSR are 0x390 only present if Zkr is implemented?
3. Is there any documentation of the remaining bits in `mseccnf`? I can't find any other details about it.

Thanks.

**Comment by ben-marshall** [comment]
Hi @JamesKenneyImperas 

Yes, this is a typo, it should have read `mseccfg`.

The `mseccfg` register is defined / owned by the TEE task group. They let us have a single bit in it because it seemed like a logical place to put the `SKES` bit. I realise now the spec could do with expanding on what this register is and when it exists. Something like the following:

> `mseccfg` exists if `Zkr` is implemented, or if any of the "additional functionalities from the TEE group" (I'll describe these better later) are implemented. If `Zkr` is _not_ implemented, the `SKES` bit must be hardwired to zero. If `Zkr` is implemented and "the TEE functionality" is not implemented, all bits other than `SKES` must be hardwired to zero, or otherwise set according to the TEE specifications for a not implemented feature.

Would this have answered your above question? Baring exactly what the other bits do?

Cheers,
Ben

**Comment by JamesKenneyImperas** [comment]
Hi Ben,

Yes, that would have helped. Thanks!

**Comment by ben-marshall** [comment]
Great, I'll add that in for the next release.

**Comment by mickflemm** [comment]
We switched mseccfg address to 0x747 as requested by Opcode and Consistency review.
