### ISSUE TITLE
Discussion around the need for two `vsha2c` versions

### ISSUE THREAD

**Issue by nibrunie** [riscv/riscv-crypto#213]
The current version of the standard (https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vsha2c.adoc)  specifies two versions for the SHA-2 compression: `vsha2ch` and `vsha2cl`, those instructions only differ by which part of the message schedule inputs (low or high part of the input vector they consider).
There is a not stating:
>  NB: We are currently proposing that the two variants of this instruction be
differentiated by the suffixes h and l.

Some argument in favor of keeping the instructions:
- keeping two instructions helps both `VLEN=128` and `VLEN=256` implementations:
   - for SHA-256 (`zvknh[ab]`, SEW=32), the dual-instruction saves:
      -  a `vslidedown` for VLEN=128 between each compression instruction    
      -  a `vslidedown` for VLEN=256 between each other compression instruction    
    -  for SHA-512 (`zvknh[b]`, SEW=64), the dual-instruction saves:
      -  a `vslidedown` for VLEN=256 between each compression instruction
      - nothing for VLEN=128 since no slide is required (the two pairs of message schedule words belong to different vector registers)

**Comment by kdockser** [comment]
Thanks for raising this issue Nicolas. We are currently evaluating the impact on performance of having these two instructions vs inserting the vslidedown between the compression instructions.

Since there is already a note in the specification that is keeping this issue open (see below), and because all issues need to be closed before we got to architectural review, I am closing this issue. We will update the spec soon when we have more information on the value of having the two versions of this instruction.

> Question
> Do we need two versions? We are evaluating if there is an advantage to having both as opposed
> to having one version and using a slideDown or the like between invocations.
