### ISSUE TITLE
Potential inconsistency in overlap constraint in `vaes*` instructions

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#233]
raised by @timhsu404
Is there a reason why overlapping constraint between `vd` and `vs2` are different between `vaesef` and other `vaes*` instructions 
https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vaesef.adoc does not mention

> The instruction encoding is reserved if vector register group vd overlaps with vs2.

while it is mentionned in `vaesm` for example https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vaesem.adoc

**Comment by kdockser** [comment]
The AES instruction descriptions were out of sync. I have updated them to be more in sync; I still have some work to do in this area.

The overlap constraints were too strict in some cases and in others they were part of a note. Since notes are non-normative, we should not put such requirements in them. These have all be cleaned up.
