### ISSUE TITLE
Data independent timing for Zvbb and Zvbc

### ISSUE THREAD

**Issue by nhukc** [riscv/riscv-crypto#315]
The bit manipulation instructions (Zvbb, Zvbc) should be data independent as well. Key material flows through these instructions when implementing algorithms which rely on finite field multiplications. For example, a GHASH implementation without Zvkg.

This is especially relevant for POLYVAL in AES-GCM-SIV and AES-HCTR2 modes.

**Comment by nibrunieAtSi5** [comment]
Those instructions are included in `Zvkt` https://github.com/riscv/riscv-crypto/blob/master/doc/vector/riscv-crypto-vector-zvkt.adoc . They are not mandated to expose data independent timing if `Zvkt` is not supported because (IIRC) the task group did not want to put too much burden on implementations not interested by cryptography (at least not in resistance against timing attack). But for implementations targetting such resistance, they will implement `Zvkt` and so `Zvbb` and `Zvbc` must enforce data independent timing.
