### ISSUE TITLE
vghsh vs vgmul

### ISSUE THREAD

**Issue by aamartin0000** [riscv/riscv-crypto#332]
If I correctly understand the Sail code in the spec, isn't vgmul functionally the same as vghsh, with vs1=0?  If so, would it be worth saving an opcode, instead having a "vx" version of vghsh?  There could be an assembler pseudo op that equates vgmul.vv to "vghsh.vx vd,vs2,x0".

**Comment by nibrunieAtSi5** [comment]
I think this was considered. One of the issue is that the `.vx` version would only make sense for `x0`, as for standard implementations (ELEN,XLEN=64) the scalar register would be too small to fit anything useful (except 0). It may be better to keep the encoding with func3 for `.vx` for another operation which can benefit fully from this form.

**Comment by aamartin0000** [comment]
Ok, that's fair.  Would it be worth adding a note to the vgmul spec mentioning this?  It might be a useful hint for implementation and verification.

**Comment by aamartin0000** [comment]
That should be good enough!  I didn't go back to this spec after I wrote my rtl code.

I'll go ahead and close this issue.
